### ISSUE TITLE
画面をマップ全表示する

### ISSUE THREAD

**Issue by ssakura0407** [ssakura0407/sotsusei2017#2]

**Comment by ssakura0407** [comment]
[CSSでフルスクリーン(全画面) ＋ 縦横中央配置レイアウトを作る【3ステップ + おまけ】 | maesblog](https://mae.chab.in/archives/2749)

```css
.box {
  width: 100vw;
  height: 100vh;
}
```

で対応
